namespace Alkahest.Core.Game
{
    public enum ActionEndKind : uint
    {
        Unknown1 = 0,
        CancelLockOn = 1,
        Cancel = 2,
        SpecialInterrupt = 3,
        Chain = 4,
        Retaliate = 5,
        Interrupt = 6,
        Unknown2 = 8,
        Unknown3 = 9,
        ButtonRelease = 10,
        ButtonReleaseChain = 11,
        ResourceDepleted = 13,
        Unknown4 = 15,
        InvalidTarget = 19,
        Unknown5 = 23,
        Unknown6 = 24,
        Unknown7 = 25,
        Unknown8 = 28,
        TerrainInterrupt = 29,
        Unknown9 = 33,
        LockOnCast = 36,
        LoadInterrupt = 37,
        DashEnd = 39,
        MovieInterrupt = 43,
        Unknown10 = 49,
        ButtonReleaseFinished = 51,
        Unknown11 = 52,
        Unknown12 = 55,
        Unknown13 = 56,
    }
}
