namespace Alkahest.Core.Game
{
    public enum ChatChannel : uint
    {
        Say = 0,
        Party = 1,
        Guild = 2,
        Area = 3,
        Trade = 4,
        Team = 5,
        Whisper = 7,
        Greeting = 9,
        Fishing = 10,
        Private1 = 11,
        Private2 = 12,
        Private3 = 13,
        Private4 = 14,
        Private5 = 15,
        Private6 = 16,
        Private7 = 17,
        Private8 = 18,
        Bargain = 19,
        LFG = 20,
        PartyNotice = 21,
        LeaderNotice = 22,
        System = 24,
        RaidNotice = 25,
        Emote = 26,
        Global = 27,
        Raid = 32,
        Hit = 101,
        CriticalHit = 102,
        MinionDamage = 103,
        CriticalMinionDamage = 104,
        FallDamage = 105,
        MonsterDamage = 106,
        CriticalMonsterDamage = 107,
        BossDamage = 108,
        CriticalBossDamage = 109,
        Alert = 201,
        WorldAlert = 202,
        Notice = 203,
        PartyAlert = 204,
        GuildAlert = 205,
        TeamAlert = 206,
        UIAlert = 207,
        Warning = 208,
        Experience = 210,
        Gold = 211,
        RolePlay = 212,
        Megaphone = 213,
        GuildAdvertising = 214,
        RestrictedLFG = 215,
        CommonItem = 216,
        UncommonItem = 217,
        RareItem = 218,
        SuperiorItem = 219,
    }
}
